config/routes.rb
Rails.application.routes.draw do

  resources :resumes, only: [:index, :new, :create, :destroy]

  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  devise_for :users
  resources :articles

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"
  get '/contact' => 'pages#contact'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  resourcify
end

app/models/resume.rb
class Resume < ApplicationRecord
	mount_uploader :attachment, AttachmentUploader
	validates :name, presence: true
	resourcify
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/controllers/_users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # check_authorization

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to main_app.root_url, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :summary, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		@home_dir = String(Rails.root) + '/app'
		@home_info_file = 'home_info'
		@lastest_projects = Article.limit(10).order('created_at desc')

		@page_info = JSON.parse File.open(@home_dir + "/assets/jsons/#{@home_info_file}.json").read
	end

	def index_users
		
	end

	def contact

	end

	def login

	end

	def register

	end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
    @resumes = Resume.all
  end
   
  def new
    @resume = Resume.new
  end
   
  def create
    @resume = Resume.new(resume_params)
    @resume.user_id = current_user.id
    
    if @resume.save
        redirect_to resumes_path, notice: "The file #{@resume.name} has been uploaded."
      else
         render "new"
      end
      
   end
   
   def destroy
      @resume = Resume.find(params[:id])
      @resume.destroy
      redirect_to resumes_path, notice:  "The file #{@resume.name} has been deleted."
   end
   
   private
      def resume_params
      params.require(:resume).permit(:name, :attachment)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :article_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :article_body %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_field :summary, id: :article_summary %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proyectos recientes:</h1>

<% if @articles.length > 0 %>
  <table class="index-table">
    <thead>
      <tr>
        <th>Titulo</th>
        <th>Cuerpo</th>
        <th>Descripcion</th>
        <th>Encargado</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= link_to article.title, article %></td>
          <td><%= article.body %></td>
          <td><%= article.summary %></td>
          <td><%= article.user.email%></td>
          <% if user_signed_in? %>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <span class="info-empty-list">
    Oh Oh... No hay proyectos registrados aun.
  </span>
<% end %>

<br/>

<% if user_signed_in? and 
      current_user.has_role? "poster" %>
    <strong>
      <%= link_to "Publicar articulo", new_article_path , style: "color: blue", class: "btn btn-primary"%>
    </strong>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @article.title %>
</h1>

<br/>

<section id="article-summary">
	<%= @article.summary %>
</section>

<br/>

<section id="article-body">
	<%= @article.body %>
</section>

<p>
  <small>Publicado por:</small>
  <small><%= link_to @article.user.email, @article.user %></small>
</p>
<p>
  <small>Encargado:</small>
  <small><%= link_to @article.user.username, @article.user %></small>
</p>

<% if user_signed_in? and current_user.has_role? :poster %>
  <br/>
  <%= link_to 'Edit', edit_article_path(@article) %>
  <%= button_to "Delete",  @article, method: :delete, class: "btn btn-danger",
  confirm: "Are you sure that you wish to delete this article?" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>UCOM</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    
  </head>
  <body>
  <% if params.has_key? :debug %>
    <%= console %>
  <% end %>
    <header>
      <a id="page-logo" href="/">UCOM</a>
      <nav id="navbar">
          <li>
            <a href="/articles">Proyectos</a>
          </li>
          <li>
            <a href="/contact">Contacto</a>
          </li>
          <li>
            <a href="/resumes">Biblioteca</a>
          </li>
      </nav>
      <section id = "navbar-right-container" class="pull-right">
        <span id="navbar-text">
        <% if user_signed_in? %>
          Usuario actual: <strong><%= current_user.email %></strong>.
          <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Iniciar sesion", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
        </span>
      </section>

    </header>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <main id="wrapper">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/contact.html.erb
<h1>Contacto</h1>
<br/>

<strong>Direccion</strong>
<p>
	Enitel 4C 1/2  al Sur contiguo a farmacia Divino Niño, Somoto
</p>
<br/>
<strong>Telefono:</strong>
<a href="#">+505 27220947</a>

<br/>

<p>
	<strong>Correo Electronico:</strong>
	<a href="#">info@ucom.org.ni</a>
</p>

app/views/pages/home.html.erb
<h1 id="home-title">
	Pagina de inicio para UCOM
</h1>

<br/>

<section class="articles-container content-block">
	<h2 class="articles-container-title">Proyectos recientes:</h3>
	<ul class="articles-list">
		<% @lastest_projects.each do |project| %>
			<li linksto="<%= article_path(project) %>" class="articles-item linkable">
				<% title_size = 25 %>
    			<span class="articles-item-title">
    				<%= project.title[0..title_size] %>
    				<% if project.title.length > title_size %>
    				...
    				<% end %>
    			</span>
    			<span class="articles-item-desc">
    				<small>
    					<%= project.summary[0..25] %><% if project.summary.length > 25 %>...
	    				<% end %>
    				</small>|
    				<small>
    					<%= project.created_at.strftime("%F %H:%M") %>
    				</small>
    			</span>
			</li>
		<% end %>
	</ul>
</section>
<br/>
<hr/>

<section class="org-info">
	<h2>
		Informacion de UCOM
	</h2>
	<% @page_info.each do |info_item| %>
		<section class="org-info-item content-block">
			<h2 class="org-info-item-title">
				<%= info_item['title'] %>
			</h2>

			<section class="org-info-text" style="white-space: pre-wrap"><%= info_item['text'] %></section>
			
		</section>
	<% end %>
</section>

app/views/pages/user_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarion actuales</h1>

app/views/resumes/index.html.erb
<% if !flash[:notice].blank? %>
   <div>
    <%= flash[:notice] %>
   </div>
<% end %>

<h1> Biblioteca </h1>

<% if !@resumes.empty? %>
  <section class="index-table">
    <table>
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Usuario</th>
          <th>Descarga</th>
          <th> </th>
        </tr>
      </thead>
      
      <tbody>
        <% @resumes.each do |resume| %>
          <tr>
          <td><%= resume.name %></td>
          <td><%= User.find(resume.user_id).email %></td>
          <td><%= link_to "Descargar archivo", resume.attachment_url %></td>
          <% if user_signed_in? and resume.user_id == current_user.id %>
            <td><%= button_to "Borrar",  resume, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
          <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>

<% else %>

  <span class="info-empty-list">
    Oh Oh... No hay archivos subidos aun.
  </span>

<% end %>

<br/>

<% if user_signed_in? and current_user.has_role? :poster %>
  <strong>
    <%= link_to "Subir Archivo", new_resume_path, style:"color:blue", class: "btn btn-primary" %>
  </strong>
  <br />
<% end %>

app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @resume.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<h1> Biblioteca – Subir Archivo </h1>

<div class = "well">
   <%= form_for @resume, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save" %>
   <% end %>
</div>

app/views/users__/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  <b>Hello?</b>
<% end %>

app/views/users__/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users__/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td> 
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users__/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<% debug @user %>

<%= link_to 'Back', users_path %>

app/views/users__/show.html.erb
<p id="notice"><%= notice %></p>

<p id="username">
  <strong><%= @user.name %></strong>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>